### PR TITLE
Todos

### PR DESCRIPTION
**Pull request by xsaurabhsuthar**
* Added Todo item with custom checkbox.
image
image
* Task creation form with custom range slider and input fields.
image
image

### CODE REVIEW

**Review by znjs — APPROVED** [review]
- Clean code
- very easy to understand the code
- Clean Styled Components
- Good naming conventions used 👍👍

**Comment by znjs** [comment]
image
Layout breaking on add action

**Review by Pratik1005 — APPROVED** [review]
Nice UI, good code structure

**Comment by xsaurabhsuthar** [comment]
Thanks @znjs and @Pratik1005 for review. Will fix the UI in modal.

**Pull request merged**
